/** agentic · code：单点编程任务（单文件/单 bug/短改动），无需多步编排 */
export const AGENTIC_CODE: string[] = [
  '修一下 src/index.ts 的类型报错',
  '帮我改这个 bug',
  '这个函数单测怎么写',
  'fix package.json 里的依赖版本',
  '把这个 any 改成明确类型',
  '给 UserService 补一个单元测试',
  '解决 Cannot find module 报错',
  '修一下这个 TypeError',
  '帮我看下这段代码为什么空指针',
  '优化一下这个函数的可读性',
  '把 var 改成 const/let',
  '给这个接口补 JSDoc',
  '修一下 eslint 报的 unused var',
  '帮我写一个 debounce 工具函数',
  '把回调改成 async/await',
  '修复这个 Promise 没有 catch 的问题',
  '帮我改一下正则匹配邮箱',
  '给这个组件加 loading 状态',
  '修一下路由 404 跳转',
  '帮我把 console.log 清掉',
  '修复这个 CSS 布局错位',
  '给按钮加防重复点击',
  '修一下表单校验逻辑',
  '帮我写一个简单的 zod schema',
  '把这个 hardcode 抽成常量',
  '修一下日期格式化错误',
  '帮我看这个 diff 有没有明显问题',
  '给这个 API 调用加超时',
  '修复测试里 flaky 的断言',
  '帮我改一下 import 路径别名',
  '修一下 Windows 路径分隔符问题',
  '给这个 hook 补依赖数组',
  '帮我写一段解析 query string 的代码',
  '修一下内存泄漏可疑的闭包引用',
  '把这个同步读写改成 fs/promises',
  '帮我生成这个函数的测试用例骨架',
]
