export {
  createRouterAgent,
  type CreateRouterAgentOptions,
  type RouterAgent,
  type RouterDecision,
  type RouterDecidedBy,
  type RouterInput,
} from './agent'

export {
  runL1,
  decideL1,
  extractFacts,
  decideBySemantic,
  cosineSimilarity,
  DEFAULT_PROTOTYPES,
  prototypeStats,
  prototypeTotal,
  ROUTE_PROTOTYPE_TABLE,
  listRoutePrototypeDocs,
  getRoutePrototypeCorpusVersion,
  getRoutePrototypeSeed,
  type Prototype,
  type RoutePrototypeDoc,
  type RoutePrototypeDocMeta,
  type RoutePrototypeSeed,
  isGreetingOnly,
  isSelfIntro,
  OFFICE_KEYWORDS,
  CODE_KEYWORDS,
  MULTI_STEP_KEYWORDS,
  type EmbedPort,
  type PrototypeSearchHit,
  type PrototypeSearchPort,
  type Facts,
  type L1Attachment,
  type L1Decision,
  type L1Input,
  type L1Options,
  type L1Pass,
  type L1Result,
  type L1Thresholds,
} from './l1'

export {
  classifyL2,
  runL2,
  parseL2Judgement,
  policyForBand,
  buildL2Messages,
  summarizeHistory,
  L2RawSchema,
  L2_FEW_SHOTS,
  L2_PROMPT_VERSION,
  L2_DEFAULT_TIMEOUT_MS,
  type L2Attachment,
  type L2Decision,
  type L2HistoryTurn,
  type L2Input,
  type L2Judgement,
  type L2Options,
  type L2Result,
  type L2Unavailable,
} from './l2/index'

export {
  classifyL3,
  runL3,
  parseL3Judgement,
  buildL3Messages,
  invokeL3,
  describeTrigger,
  liftLane,
  liftBand,
  resolveL3,
  SYSTEM_PROMPT as L3_SYSTEM_PROMPT,
  L3RawSchema,
  L3_PROMPT_VERSION,
  L3_DEFAULT_TIMEOUT_MS,
  L3_DEFAULT_ACCEPT,
  L3_DEFAULT_ESCALATE,
  type BuildL3MessagesOptions,
  type InvokeL3Options,
  type L3Attachment,
  type L3Decision,
  type L3HistoryTurn,
  type L3Input,
  type L3Judgement,
  type L3Options,
  type L3Prior,
  type L3Resolution,
  type L3Result,
  type L3Thresholds,
  type L3Unavailable,
} from './l3/index'

export {
  applySafetyFloor,
  buildCacheKey,
  createRouteCache,
  extractDirective,
  hashString,
  normalizeText,
  resolveLock,
  runL0,
  safetyScan,
  DEFAULT_BAND,
  DIRECTIVES,
  type Domain,
  type L0Context,
  type L0Input,
  type L0Result,
  type Lane,
  type LockSpec,
  type ParsedDirective,
  type RouteCacheOptions,
  type RouteCore,
} from './l0'

export { DEFAULT_SAFETY_RULES } from './rules/l0'

export {
  type Band,
  type ModelStrength,
  type ModelTier,
  type SafetyCategory,
  type SafetyResult,
  type SafetyRule,
  type SafetyVerdict,
  type ToolsPolicy,
} from './types'

export {
  checkBudget,
  deriveBudget,
  DEFAULT_BUDGET_TABLE,
  BUDGET_UNLIMITED,
  EMPTY_USAGE,
  type BudgetPolicy,
  type BudgetSpec,
  type BudgetUsage,
  type BudgetVerdict,
} from './l0/budget'

export { hasAnaphora, ANAPHORA_RE } from './signals/anaphora'
