import type { IpcChannelSignature } from './ast/controller-scanner'

/**
 * Build a preload script that exposes `window.api` via `@electrum/preload`
 * and documents the known `@IpcHandle` channel allowlist.
 */
export function buildPreloadScript(channels: IpcChannelSignature[]): string {
  const channelLiterals = channels.map((c) => `  '${c.channel}',`).join('\n')

  return `// AUTO-GENERATED — DO NOT EDIT
// Generated by @electrum/codegen
import { exposeApi } from '@electrum/preload'

/** Channels registered via @IpcHandle (documentation / allowlists) */
export const IPC_INVOKE_CHANNELS = [
${channelLiterals}
] as const

export type IpcInvokeChannel = (typeof IPC_INVOKE_CHANNELS)[number]

exposeApi()
`
}
