import type { IpcChannelSignature } from './ast/controller-scanner'

export interface BuildDeclarationOptions {
  /** Include Window.api global declaration (default: false) */
  includeGlobal?: boolean
}

export function buildIpcApiDeclaration(
  channels: IpcChannelSignature[],
  options: BuildDeclarationOptions = {},
): string {
  const methods = channels
    .map((c) => {
      const params = c.params.length > 0 ? c.params : ''
      const sig = `(${params}) => ${c.returnType}`
      return `  /** IPC: ${c.channel} (${c.controller}.${c.method}) */\n  '${c.channel}': ${sig}`
    })
    .join('\n\n')

  const ipcApi = `export interface IpcApi {
${methods}
}`

  if (!options.includeGlobal) {
    return `${banner()}\n${ipcApi}\n`
  }

  return `${banner()}${ipcApi}

export interface ElectronAPI {
  invoke: <K extends keyof IpcApi>(
    channel: K,
    ...args: Parameters<IpcApi[K]>
  ) => ReturnType<IpcApi[K]>
  on: (channel: string, listener: (...args: unknown[]) => void) => () => void
  send: (channel: string, ...args: unknown[]) => void
}

declare global {
  interface Window {
    api: ElectronAPI
  }
}

export {}
`
}

function banner(): string {
  return `// AUTO-GENERATED — DO NOT EDIT
// Generated by @electrum/codegen
`
}
