// AUTO-GENERATED — DO NOT EDIT
// Generated by @electrum/codegen

export interface IpcApi {
  /** IPC: app:info (AppController.info) */
  'app:info': () => Promise<{ name: string; version: string; electron: string; node: string; chrome: string; platform: string }>

  /** IPC: app:ping (AppController.ping) */
  'app:ping': (message: string) => Promise<{ echo: string; at: number }>

  /** IPC: chat:clear (ChatController.clear) */
  'chat:clear': () => Promise<{ ok: boolean }>

  /** IPC: chat:history (ChatController.history) */
  'chat:history': () => Promise<{ id: string; role: "user" | "assistant"; content: string; at: number }[]>

  /** IPC: chat:send (ChatController.send) */
  'chat:send': (content: string) => Promise<{ id: string; role: "user" | "assistant"; content: string; at: number }>

  /** IPC: settings:get (SettingsController.get) */
  'settings:get': () => Promise<{ theme: "light" | "dark" | "system"; model: string; language: string; sendOnEnter: boolean }>

  /** IPC: settings:reset (SettingsController.reset) */
  'settings:reset': () => Promise<{ theme: "light" | "dark" | "system"; model: string; language: string; sendOnEnter: boolean }>

  /** IPC: settings:set (SettingsController.set) */
  'settings:set': (patch: { theme?: "light" | "dark" | "system"; model?: string; language?: string; sendOnEnter?: boolean }) => Promise<{ theme: "light" | "dark" | "system"; model: string; language: string; sendOnEnter: boolean }>

  /** IPC: window:close (WindowController.close) */
  'window:close': () => Promise<void>

  /** IPC: window:focus (WindowController.focus) */
  'window:focus': (id: number) => Promise<boolean>

  /** IPC: window:isMaximized (WindowController.isMaximized) */
  'window:isMaximized': () => Promise<boolean>

  /** IPC: window:list (WindowController.list) */
  'window:list': () => Promise<{ id: number; title: string; focused: boolean }[]>

  /** IPC: window:minimize (WindowController.minimize) */
  'window:minimize': () => Promise<void>

  /** IPC: window:toggleMaximize (WindowController.toggleMaximize) */
  'window:toggleMaximize': () => Promise<boolean>
}
