import { defineMcpTools } from './build'
import { TOOL_CATALOG_GROUPS } from './groups'

const PLAYWRIGHT = TOOL_CATALOG_GROUPS.find((g) => g.id === 'mcp_playwright')!

/**
 * Playwright MCP 子工具（70+）。默认集仅保留高频交互子集（约 12 个），
 * 其余（tracing / video / storage / verify / run_code_unsafe 等）按需挂载，
 * 由向量召回或显式白名单触发，避免默认绑定膨胀。
 */
export const PLAYWRIGHT_TOOLS = defineMcpTools(PLAYWRIGHT, [
  { tool: 'browser_navigate', description: '浏览器打开/跳转到 URL。访问网站、打开链接。navigate goto open url page.' },
  { tool: 'browser_navigate_back', description: '浏览器历史后退。上一页、返回。go back history.', defaultEnabled: false },
  { tool: 'browser_navigate_forward', description: '浏览器历史前进。下一页。go forward history.', defaultEnabled: false },
  { tool: 'browser_reload', description: '刷新当前页面。reload refresh page.', defaultEnabled: false },
  { tool: 'browser_close', description: '关闭当前页面/浏览器。close browser tab page.' },
  { tool: 'browser_resize', description: '调整浏览器窗口大小。resize viewport window.', defaultEnabled: false },
  { tool: 'browser_snapshot', description: '捕获页面无障碍树快照（交互首选，优于截图）。page a11y snapshot accessibility tree.' },
  { tool: 'browser_take_screenshot', description: '截取当前页截图（勿据此点击，交互用 snapshot）。screenshot capture page image.' },
  { tool: 'browser_click', description: '点击页面元素（需 snapshot 的 ref）。click button link.' },
  { tool: 'browser_drag', description: '在两元素间拖拽。drag drop element.', defaultEnabled: false },
  { tool: 'browser_drop', description: '向外拖入文件或 MIME 数据到元素。drop files onto element.', defaultEnabled: false },
  { tool: 'browser_hover', description: '悬停在元素上。hover mouse over.', defaultEnabled: false },
  { tool: 'browser_type', description: '向可编辑元素输入文本。type fill input textbox.' },
  { tool: 'browser_press_key', description: '按下键盘按键（如 Enter、Tab）。press key keyboard.' },
  { tool: 'browser_press_sequentially', description: '逐键输入文本。type key by key sequentially.', defaultEnabled: false },
  { tool: 'browser_keydown', description: '按住键不放。keydown hold key.', defaultEnabled: false },
  { tool: 'browser_keyup', description: '松开按键。keyup release key.', defaultEnabled: false },
  { tool: 'browser_select_option', description: '下拉框选择选项。select dropdown option.' },
  { tool: 'browser_check', description: '勾选复选框或单选。check checkbox radio.', defaultEnabled: false },
  { tool: 'browser_uncheck', description: '取消勾选复选框。uncheck checkbox.', defaultEnabled: false },
  { tool: 'browser_fill_form', description: '批量填写多个表单字段。fill form fields.' },
  { tool: 'browser_file_upload', description: '上传一个或多个文件。upload file input.', defaultEnabled: false },
  { tool: 'browser_handle_dialog', description: '处理 alert/confirm/prompt 对话框。accept dismiss dialog.', defaultEnabled: false },
  { tool: 'browser_evaluate', description: '在页面或元素上执行 JavaScript。evaluate js in page.', defaultEnabled: false },
  { tool: 'browser_find', description: '在当前 snapshot 中按文本/正则查找节点与 ref。find search in snapshot.', defaultEnabled: false },
  { tool: 'browser_wait_for', description: '等待文本出现/消失或指定时长。wait for text timeout.' },
  { tool: 'browser_tabs', description: '列出/新建/关闭/切换浏览器标签。manage tabs.' },
  { tool: 'browser_console_messages', description: '获取页面 console 日志。console messages logs.' },
  { tool: 'browser_console_clear', description: '清空 console 消息缓冲。clear console.', defaultEnabled: false },
  { tool: 'browser_network_requests', description: '列出页面加载以来的网络请求。list network requests.', defaultEnabled: false },
  { tool: 'browser_network_request', description: '查看单条网络请求详情（头/体）。network request details.', defaultEnabled: false },
  { tool: 'browser_network_clear', description: '清空网络请求记录。clear network log.', defaultEnabled: false },
  { tool: 'browser_network_state_set', description: '设置在线/离线网络状态。set online offline.', defaultEnabled: false },
  { tool: 'browser_route', description: '按 URL 模式 mock 网络请求。mock route intercept.', defaultEnabled: false },
  { tool: 'browser_route_list', description: '列出已注册的网络路由。list routes.', defaultEnabled: false },
  { tool: 'browser_unroute', description: '移除网络路由。unroute remove mock.', defaultEnabled: false },
  { tool: 'browser_pdf_save', description: '将当前页保存为 PDF。save page pdf.', defaultEnabled: false },
  { tool: 'browser_cookie_list', description: '列出 cookies。list cookies.', defaultEnabled: false },
  { tool: 'browser_cookie_get', description: '按名称获取 cookie。get cookie.', defaultEnabled: false },
  { tool: 'browser_cookie_set', description: '设置 cookie。set cookie.', defaultEnabled: false },
  { tool: 'browser_cookie_delete', description: '删除指定 cookie。delete cookie.', defaultEnabled: false },
  { tool: 'browser_cookie_clear', description: '清除全部 cookies。clear cookies.', defaultEnabled: false },
  { tool: 'browser_localstorage_list', description: '列出 localStorage。list localStorage.', defaultEnabled: false },
  { tool: 'browser_localstorage_get', description: '读取 localStorage 项。get localStorage.', defaultEnabled: false },
  { tool: 'browser_localstorage_set', description: '写入 localStorage 项。set localStorage.', defaultEnabled: false },
  { tool: 'browser_localstorage_delete', description: '删除 localStorage 项。delete localStorage.', defaultEnabled: false },
  { tool: 'browser_localstorage_clear', description: '清空 localStorage。clear localStorage.', defaultEnabled: false },
  { tool: 'browser_sessionstorage_list', description: '列出 sessionStorage。list sessionStorage.', defaultEnabled: false },
  { tool: 'browser_sessionstorage_get', description: '读取 sessionStorage 项。get sessionStorage.', defaultEnabled: false },
  { tool: 'browser_sessionstorage_set', description: '写入 sessionStorage 项。set sessionStorage.', defaultEnabled: false },
  { tool: 'browser_sessionstorage_delete', description: '删除 sessionStorage 项。delete sessionStorage.', defaultEnabled: false },
  { tool: 'browser_sessionstorage_clear', description: '清空 sessionStorage。clear sessionStorage.', defaultEnabled: false },
  { tool: 'browser_storage_state', description: '保存 cookies/localStorage 到文件。save storage state.', defaultEnabled: false },
  { tool: 'browser_set_storage_state', description: '从文件恢复 storage state。restore storage state.', defaultEnabled: false },
  { tool: 'browser_mouse_move_xy', description: '移动鼠标到坐标。mouse move xy.', defaultEnabled: false },
  { tool: 'browser_mouse_down', description: '鼠标按下。mouse down.', defaultEnabled: false },
  { tool: 'browser_mouse_up', description: '鼠标抬起。mouse up.', defaultEnabled: false },
  { tool: 'browser_mouse_wheel', description: '滚轮滚动。mouse wheel scroll.', defaultEnabled: false },
  { tool: 'browser_mouse_click_xy', description: '在坐标点击。click at xy.', defaultEnabled: false },
  { tool: 'browser_mouse_drag_xy', description: '拖拽鼠标到坐标。drag mouse xy.', defaultEnabled: false },
  { tool: 'browser_highlight', description: '高亮页面元素。highlight element overlay.', defaultEnabled: false },
  { tool: 'browser_hide_highlight', description: '取消元素高亮。hide highlight.', defaultEnabled: false },
  { tool: 'browser_annotate', description: '标注模式：用户手动画标注后返回截图与注解。annotate page dashboard.', defaultEnabled: false },
  { tool: 'browser_generate_locator', description: '为元素生成 Playwright locator（测试用）。generate locator.', defaultEnabled: false },
  { tool: 'browser_get_config', description: '获取合并后的 Playwright MCP 配置。get mcp config.', defaultEnabled: false },
  { tool: 'browser_resume', description: '恢复暂停的脚本执行（可单步）。resume paused script.', defaultEnabled: false },
  { tool: 'browser_start_recording', description: '开始录制用户操作为 Playwright 代码。start action recording.', defaultEnabled: false },
  { tool: 'browser_stop_recording', description: '停止录制并返回 Playwright 代码。stop recording get code.', defaultEnabled: false },
  { tool: 'browser_start_tracing', description: '开始 Playwright trace 录制。start tracing.', defaultEnabled: false },
  { tool: 'browser_stop_tracing', description: '停止 trace 录制。stop tracing.', defaultEnabled: false },
  { tool: 'browser_start_video', description: '开始视频录制。start video recording.', defaultEnabled: false },
  { tool: 'browser_stop_video', description: '停止视频录制。stop video.', defaultEnabled: false },
  { tool: 'browser_video_chapter', description: '在视频中加入章节卡片标记。video chapter marker.', defaultEnabled: false },
  { tool: 'browser_video_show_actions', description: '视频中显示操作标注叠加层。show action overlays on video.', defaultEnabled: false },
  { tool: 'browser_video_hide_actions', description: '关闭操作标注叠加层。hide action overlays.', defaultEnabled: false },
  { tool: 'browser_verify_element_visible', description: '断言元素可见。verify element visible.', defaultEnabled: false },
  { tool: 'browser_verify_list_visible', description: '断言列表可见。verify list visible.', defaultEnabled: false },
  { tool: 'browser_verify_text_visible', description: '断言文本可见。verify text visible.', defaultEnabled: false },
  { tool: 'browser_verify_value', description: '断言元素值。verify element value.', defaultEnabled: false },
  {
    tool: 'browser_run_code_unsafe',
    description: '在服务端执行任意 Playwright 代码（不安全/等价 RCE）。unsafe run playwright code.',
    defaultEnabled: false,
  },
])
