import type { ToolCatalogEntry } from '../types'

/** 非 MCP 工具（community / builtin）：不分组（无 groupId / mcp） */
export const CORE_TOOLS: readonly ToolCatalogEntry[] = [
  // —— 搜索 / 联网 ——
  {
    id: 'duckduckgo_search',
    category: 'search',
    title: 'DuckDuckGo 搜索',
    description: '轻量联网检索（community）；默认关闭——优先用 mcp_modsearch（内置 DDG 兜底）。',
    source: '@langchain/community/tools/duckduckgo_search',
    defaultEnabled: false,
    keywords: ['联网搜索', '搜索', 'duckduckgo', 'ddg', 'web search'],
  },
  {
    id: 'brave_search',
    category: 'search',
    title: 'Brave Search',
    description: 'Brave 联网搜索（需 BRAVE_SEARCH_API_KEY）。',
    source: '@langchain/community/tools/brave_search',
    defaultEnabled: false,
    requiresSecret: 'brave',
    keywords: ['联网搜索', '搜索', 'brave', 'web search'],
  },
  {
    id: 'serp_search',
    category: 'search',
    title: 'SerpAPI',
    description: 'Google 等结果聚合（需 SERPAPI_API_KEY）。',
    source: '@langchain/community/tools/serpapi',
    defaultEnabled: false,
    requiresSecret: 'serp',
    keywords: ['联网搜索', '搜索', 'google', 'serp', 'serpapi'],
  },
  // —— 计算 & 代码 ——
  {
    id: 'calculator',
    category: 'compute',
    title: '计算器',
    description: '求值数学表达式。',
    source: '@langchain/community/tools/calculator',
    defaultEnabled: true,
    keywords: ['计算', '算数', '求值', '数学', '表达式', 'calculator', 'math'],
  },
  {
    id: 'js_eval',
    category: 'compute',
    title: '受限 JS 求值（builtin）',
    description: 'node:vm 短 JS（无 IO / 无 require）；默认关闭——优先 mcp_vmsandbox。',
    source: 'builtin',
    defaultEnabled: false,
    keywords: ['执行代码', '求值', 'javascript', 'js', 'eval'],
  },
  {
    id: 'wolfram_alpha',
    category: 'compute',
    title: 'Wolfram Alpha',
    description: '符号计算与知识问答（需 WOLFRAM_ALPHA_APPID）。',
    source: '@langchain/community/tools/wolframalpha',
    defaultEnabled: false,
    requiresSecret: 'wolfram',
    keywords: ['符号计算', '数学', '积分', '知识问答', 'wolfram', 'alpha'],
  },
  // —— 网页解析 ——
  {
    id: 'fetch_url',
    category: 'web',
    title: '抓取网页文本',
    description: 'HTTP GET 后去标签截断；复杂交互优先走 mcp_playwright / modsearch read_page。',
    source: 'builtin',
    defaultEnabled: true,
    keywords: ['抓取网页', '打开链接', '读文章', '爬页面', 'fetch', 'url', '网页正文'],
  },
  // —— 资讯 & 金融 ——
  {
    id: 'google_trends',
    category: 'news_finance',
    title: 'Google Trends',
    description: '兴趣趋势（经 SerpAPI，需密钥）。',
    source: '@langchain/community/tools/google_trends',
    defaultEnabled: false,
    requiresSecret: 'serp',
    keywords: ['趋势', '热搜', '兴趣趋势', '热度', 'trends', 'google trends'],
  },
  // —— 数据库 ——
  {
    id: 'sqlite_query',
    category: 'database',
    title: 'SQLite 只读查询',
    description: '对工作区内 .db/.sqlite 执行 SELECT（node:sqlite）。',
    source: 'builtin',
    defaultEnabled: true,
    requiresWorkspace: true,
    keywords: ['数据库', '查询', 'sql', 'select', 'sqlite', 'db', '表'],
  },
  // —— 知识库 ——
  {
    id: 'wikipedia',
    category: 'knowledge',
    title: 'Wikipedia',
    description: '维基百科检索与摘要。',
    source: '@langchain/community/tools/wikipedia_query_run',
    defaultEnabled: true,
    keywords: ['维基百科', '百科', '词条', 'wikipedia', 'wiki', '知识'],
  },
  {
    id: 'stackexchange',
    category: 'knowledge',
    title: 'Stack Exchange',
    description: 'Stack Overflow 等站点问答检索。',
    source: '@langchain/community/tools/stackexchange',
    defaultEnabled: true,
    keywords: ['问答', '技术问答', 'stackoverflow', 'stack exchange', '报错', '解决方案'],
  },
]
